#  是否自动获取开拍提醒商品ID：0关闭，1开启
onOrOff: 0
url: https://api.m.jd.com/api?functionId=paipai.dbd.reminder.auctionList&body=%7B%22readStatus%22:%22%22,%22endStatus%22:%220%22,%22pageNo%22:1,%22pageSize%22:20,%22mpSource%22:1%7D&t=1605707289665&appid=paipai_h5
header:
  Host: api.m.jd.com
  Origin: https://paipai.m.jd.com
  Cookie: __jd_ref_cls=Mnpm_ComponentApplied; mba_muid=1605522529441285315636; mba_sid=16057070016733215373615217352.4; __jda=122270672.1605522529441285315636.1605522529.1605700871.1605707001.13; __jdb=122270672.4.1605522529441285315636|13.1605707001; __jdc=122270672; pt_key=app_openAAJfslRgADBqJBn-B0sKYmhWgm2ADl8Z9oGnWTvklWC8qDrm6pm6imcQ8JxzUbgaBjath7i7rgA; pt_pin=avvcdddd; pwdt_id=avvcdddd; sid=7271608ab35a3f1ea2effdab74054aaw; 3AB9D23F7A4B3C9B=4ECDDUXAZ5TBO2HPJWBP7MBPQIULOCOG6T4O7QCVIEU4V2VOHHLP5O6FT4526LYJE4PTQFEJXYO3BLOXNAB22NBXMI; shshshfp=3b1ef6c830182997fcde811237bc22fb; shshshfpa=67edde7a-36fc-8923-3b18-bbdb38c17145-1605573235; shshshfpb=aFD0WT0Ke6VaBCgkL1W%20KNA%3D%3D; __jdv=122270672%7Cdirect%7C-%7Cnone%7C-%7C1605522529442
  Connection: keep-alive
  Accept: '*/*'
  User-Agent: 2.2.8;JDAPPERSHOU_IOS;Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
  Accept-Language: zh-cn
  Referer: https://paipai.m.jd.com/ppdbd/pages/message/index?entryid=p0020002app190123
  Accept-Encoding: gzip, deflate, br
#  delay（最后多少毫秒出价）：建议大于600    maxOfferPrice（最大出价金额）：填写最大可接受的价格，超出该价格则不出价    priceIncrease（价格金额）：每次出价的加价金额    stableOfferPrice（是否固定金额出价）：必填，0代表不是；填入其他金额则代表以改价格出价    account（使用哪个帐号出价）：必填，从1开始一次选择出价帐号
auctionData:
  - maxOfferPrice: 600
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 7800
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 180
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 180
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 600
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 600
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 600
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 400
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 600
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 600
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 600
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1
  - maxOfferPrice: 180
    priceIncrease: 1
    stableOfferPrice: 0
    delay: 600
    account: 1