#  是否以最低价出价：0不是，1是
onOrOff: 0
url: https://api.m.jd.com/api
params:
  functionId: dbd.auction.detail.history
  body: {"usedNo":,"mpSource":1}
  t:
  appid: paipai_h5
header:
  Host: api.m.jd.com
  Connection: keep-alive
  sec-ch-ua: '"Google Chrome";v="87", " Not;A Brand";v="99", "Chromium";v="87"'
  sec-ch-ua-mobile: ?0
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
  Accept: '*/*'
  Origin: https://paipai.m.jd.com
  Sec-Fetch-Site: same-site
  Sec-Fetch-Mode: cors
  Sec-Fetch-Dest: empty
  Referer: https://paipai.m.jd.com/
  Accept-Encoding: gzip, deflate, br
  Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7

