#  auctionId（商品id）：必填，填0则此条配置不加入抢购任务    delay（最后多少毫秒出价）：建议大于600    maxOfferPrice（最大出价金额）：填写最大可接受的价格，超出该价格则不出价    priceIncrease（价格金额）：每次出价的加价金额    stableOfferPrice（是否固定金额出价）：必填，0代表不是；填入其他金额则代表以改价格出价    account（使用哪个帐号出价）：必填，从1开始一次选择出价帐号

- auctionId: 242057790
  maxOfferPrice: 10000
  priceIncrease: 1
  stableOfferPrice: 0
  delay: 600
  account: 1